<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <ProjectReference Include="..\PharmaCore.Application\PharmaCore.Application.csproj" />
    <ProjectReference Include="..\PharmaCore.Domain\PharmaCore.Domain.csproj" />
  </ItemGroup>

</Project>
